#!/usr/bin/env bash

source ~/.profile
zsh

# conda activate
# eval "$(starship init bash)"

export PATH="/Users/chloegeller/gpt3-cli:$PATH"
export OPENAI_API_KEY="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"
export PATH="/Users/chloegeller/gpt3-cli/gpt3-cli:$PATH"
export PATH="/Users/chloegeller/gpt3-cli/gpt3-cli:$PATH"
export OPENAI_API_KEY="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"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/cgeller/Applications/brew/Caskroom/miniforge/base/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/cgeller/Applications/brew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
        . "/Users/cgeller/Applications/brew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
    else
        export PATH="/Users/cgeller/Applications/brew/Caskroom/miniforge/base/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/cgeller/Applications/brew/Caskroom/miniforge/base/etc/profile.d/mamba.sh" ]; then
    . "/Users/cgeller/Applications/brew/Caskroom/miniforge/base/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

